// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: wisdom/wisdom.proto

package wisdom

import (
	pow "github.com/skillcoder/pow-protect/internal/api/sdk/pow"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest - represent word of wisdom request.
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge *pow.Challenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Proof     []byte         `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_wisdom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_wisdom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_wisdom_wisdom_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetChallenge() *pow.Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *GetRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// GetResponse - represent word of wisdom response.
type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordOfWisdom string `protobuf:"bytes,1,opt,name=word_of_wisdom,json=wordOfWisdom,proto3" json:"word_of_wisdom,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wisdom_wisdom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wisdom_wisdom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_wisdom_wisdom_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetWordOfWisdom() string {
	if x != nil {
		return x.WordOfWisdom
	}
	return ""
}

var File_wisdom_wisdom_proto protoreflect.FileDescriptor

var file_wisdom_wisdom_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x1a, 0x0d, 0x70,
	0x6f, 0x77, 0x2f, 0x70, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x6f, 0x77, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x33,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x57, 0x69, 0x73,
	0x64, 0x6f, 0x6d, 0x32, 0x3a, 0x0a, 0x06, 0x57, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x12, 0x30, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x77, 0x69, 0x73, 0x64, 0x6f,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x6f, 0x77, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x77, 0x69, 0x73, 0x64, 0x6f, 0x6d, 0x3b, 0x77, 0x69, 0x73,
	0x64, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wisdom_wisdom_proto_rawDescOnce sync.Once
	file_wisdom_wisdom_proto_rawDescData = file_wisdom_wisdom_proto_rawDesc
)

func file_wisdom_wisdom_proto_rawDescGZIP() []byte {
	file_wisdom_wisdom_proto_rawDescOnce.Do(func() {
		file_wisdom_wisdom_proto_rawDescData = protoimpl.X.CompressGZIP(file_wisdom_wisdom_proto_rawDescData)
	})
	return file_wisdom_wisdom_proto_rawDescData
}

var file_wisdom_wisdom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wisdom_wisdom_proto_goTypes = []interface{}{
	(*GetRequest)(nil),    // 0: wisdom.GetRequest
	(*GetResponse)(nil),   // 1: wisdom.GetResponse
	(*pow.Challenge)(nil), // 2: pow.Challenge
}
var file_wisdom_wisdom_proto_depIdxs = []int32{
	2, // 0: wisdom.GetRequest.challenge:type_name -> pow.Challenge
	0, // 1: wisdom.Wisdom.Get:input_type -> wisdom.GetRequest
	1, // 2: wisdom.Wisdom.Get:output_type -> wisdom.GetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wisdom_wisdom_proto_init() }
func file_wisdom_wisdom_proto_init() {
	if File_wisdom_wisdom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wisdom_wisdom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wisdom_wisdom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wisdom_wisdom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wisdom_wisdom_proto_goTypes,
		DependencyIndexes: file_wisdom_wisdom_proto_depIdxs,
		MessageInfos:      file_wisdom_wisdom_proto_msgTypes,
	}.Build()
	File_wisdom_wisdom_proto = out.File
	file_wisdom_wisdom_proto_rawDesc = nil
	file_wisdom_wisdom_proto_goTypes = nil
	file_wisdom_wisdom_proto_depIdxs = nil
}
