// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wisdom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WisdomClient is the client API for Wisdom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WisdomClient interface {
	// Get returns Word of Wisdom.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type wisdomClient struct {
	cc grpc.ClientConnInterface
}

func NewWisdomClient(cc grpc.ClientConnInterface) WisdomClient {
	return &wisdomClient{cc}
}

func (c *wisdomClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/wisdom.Wisdom/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WisdomServer is the server API for Wisdom service.
// All implementations must embed UnimplementedWisdomServer
// for forward compatibility
type WisdomServer interface {
	// Get returns Word of Wisdom.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedWisdomServer()
}

// UnimplementedWisdomServer must be embedded to have forward compatible implementations.
type UnimplementedWisdomServer struct {
}

func (UnimplementedWisdomServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWisdomServer) mustEmbedUnimplementedWisdomServer() {}

// UnsafeWisdomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WisdomServer will
// result in compilation errors.
type UnsafeWisdomServer interface {
	mustEmbedUnimplementedWisdomServer()
}

func RegisterWisdomServer(s grpc.ServiceRegistrar, srv WisdomServer) {
	s.RegisterService(&Wisdom_ServiceDesc, srv)
}

func _Wisdom_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WisdomServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wisdom.Wisdom/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WisdomServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wisdom_ServiceDesc is the grpc.ServiceDesc for Wisdom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wisdom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.Wisdom",
	HandlerType: (*WisdomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Wisdom_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wisdom/wisdom.proto",
}
