// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PowClient is the client API for Pow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PowClient interface {
	// Challenge returns initial data for proof of work challenge.
	Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
}

type powClient struct {
	cc grpc.ClientConnInterface
}

func NewPowClient(cc grpc.ClientConnInterface) PowClient {
	return &powClient{cc}
}

func (c *powClient) Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, "/pow.Pow/Challenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowServer is the server API for Pow service.
// All implementations must embed UnimplementedPowServer
// for forward compatibility
type PowServer interface {
	// Challenge returns initial data for proof of work challenge.
	Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	mustEmbedUnimplementedPowServer()
}

// UnimplementedPowServer must be embedded to have forward compatible implementations.
type UnimplementedPowServer struct {
}

func (UnimplementedPowServer) Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Challenge not implemented")
}
func (UnimplementedPowServer) mustEmbedUnimplementedPowServer() {}

// UnsafePowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowServer will
// result in compilation errors.
type UnsafePowServer interface {
	mustEmbedUnimplementedPowServer()
}

func RegisterPowServer(s grpc.ServiceRegistrar, srv PowServer) {
	s.RegisterService(&Pow_ServiceDesc, srv)
}

func _Pow_Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowServer).Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pow.Pow/Challenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowServer).Challenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pow_ServiceDesc is the grpc.ServiceDesc for Pow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pow.Pow",
	HandlerType: (*PowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Challenge",
			Handler:    _Pow_Challenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pow/pow.proto",
}
